[project]
name = "oktaflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx",
    "rich",
    "python-dotenv",
    "jwt>=1.4.0",
    "requests>=2.32.5",
]
